const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data={players:[],matches:[]},db,cloud=false,user,goalsReady=true,matchDraft={A:[],B:[]},composeSheet=[],composeMode='fair',rankingSort='points';
const cfg=()=>window.FIVES_SUPABASE_CONFIG,admins=()=>window.FIVES_ADMIN_EMAILS||[],isAdminEmail=e=>admins().includes((e||'').toLowerCase());
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const validAvatarUrl=value=>{if(!value)return true;try{return['http:','https:'].includes(new URL(value).protocol)}catch(_){return false}};
const player=n=>data.players.find(p=>p.name===n),clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const playerLabel=p=>[p?.name,p?.last_name].filter(Boolean).join(' ')||'—',labelForName=name=>playerLabel(player(name)||{name});
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const positionMeta={attaque:{label:'Attaquant',color:'#df4b45'},defense:{label:'Défenseur',color:'#397dd4'},milieu:{label:'Milieu',color:'#8b5fc7'},gardien:{label:'Gardien',color:'#e6a328'},polyvalent:{label:'Polyvalent',color:'#ed7a35'}};
const infoTexts={points:['Attribution des points','Une victoire rapporte 3 points, un match nul rapporte 1 point et une défaite 0 point. Le classement général est trié par points par défaut, puis départagé par taux de victoire, buts marqués et nombre de matchs.'],matches:['Participations','Nombre total de matchs dans lesquels le joueur figure sur la feuille de match.'],rate:['Taux de victoire','Nombre de victoires divisé par le nombre de participations, multiplié par 100.'],goals:['Buts marqués','Somme des buts attribués à ce joueur dans l’historique de ses matchs.'],ppg:['Points par match','Total des points du joueur divisé par son nombre de participations.'],mvp:['MVP','Nombre de fois où le joueur a été désigné homme du match.'],diff:['Différence de buts','Total des buts marqués par ses équipes moins le total des buts encaissés pendant ses participations.'],chance:['Chance de gagner avec ce profil','Estimation fondée sur le taux de victoire, les points par match, la différence de buts et le volume de matchs. Elle devient plus fiable avec davantage de données.']};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function admin(msg=true){let ok=cloud?isAdminEmail(user?.email):true;if(!ok&&msg)toast('Cette action est réservée aux administrateurs.');return ok}
function stats(){return data.players.map(p=>{let s={...p,m:0,w:0,d:0,l:0,motm:0,goals:0,gf:0,ga:0,recent:[]};[...data.matches].sort((a,b)=>a.date.localeCompare(b.date)).forEach(x=>{let t=x.a.includes(p.name)?'A':x.b.includes(p.name)?'B':null;if(!t)return;s.m++;let w=x.result===t,n=x.result==='N';w?s.w++:n?s.d++:s.l++;s.goals+=+x.goals?.[p.name]||0;s.gf+=t==='A'?+x.scoreA||0:+x.scoreB||0;s.ga+=t==='A'?+x.scoreB||0:+x.scoreA||0;if(x.motm===p.name)s.motm++;s.recent.push(w?'V':n?'N':'D')});s.points=s.w*3+s.d;s.rate=s.m?Math.round(s.w/s.m*100):0;s.drawRate=s.m?Math.round(s.d/s.m*100):0;s.lossRate=s.m?Math.round(s.l/s.m*100):0;s.ppg=s.m?(s.points/s.m).toFixed(2):'0.00';s.diff=s.gf-s.ga;s.recent=s.recent.slice(-5).reverse();return s})}
function teammateInsight(name){let pairs=new Map;data.matches.forEach(x=>{let side=x.a.includes(name)?'A':x.b.includes(name)?'B':null;if(!side)return;let team=side==='A'?x.a:x.b,w=x.result===side;team.filter(n=>n!==name).forEach(n=>{let r=pairs.get(n)||{games:0,wins:0};r.games++;if(w)r.wins++;pairs.set(n,r)})});return[...pairs].map(([teammate,r])=>({teammate,...r,rate:Math.round(r.wins/r.games*100)})).sort((a,b)=>b.rate-a.rate||b.games-a.games)[0]}
function strength(name){let s=stats().find(x=>x.name===name);if(!s?.m)return 50;let exp=Math.min(s.m,10)/10,perf=s.rate*.62+(+s.ppg/3*100)*.23+clamp(50+s.diff*2,15,85)*.15;return 50*(1-exp)+perf*exp}
const pos=p=>p==='attaque'?1.2:p==='milieu'?0.35:p==='defense'?-1:p==='gardien'?-1.35:0,power=t=>t.reduce((z,n)=>z+strength(n),0);
function probability(A,B){let a=power(A)/Math.max(A.length,1),b=power(B)/Math.max(B.length,1);return clamp(Math.round(100/(1+Math.exp(-(a-b)/14))),8,92)}
function avatar(p,c='avatar'){return p?.avatar_url?`<div class="${c}"><img src="${esc(p.avatar_url)}" alt="Photo de ${esc(playerLabel(p))}"></div>`:`<div class="${c}">${esc(p?.name?.[0]||p?.last_name?.[0]||'?')}</div>`}
function sortedPlayers(list,metric=rankingSort){let comparators={points:(a,b)=>b.points-a.points||b.rate-a.rate||b.goals-a.goals||b.m-a.m,rate:(a,b)=>(b.m>0)-(a.m>0)||b.rate-a.rate||b.m-a.m||b.goals-a.goals,goals:(a,b)=>b.goals-a.goals||b.rate-a.rate||b.points-a.points,mvp:(a,b)=>b.motm-a.motm||b.m-a.m,attendance:(a,b)=>b.m-a.m||b.points-a.points};return[...list].sort((a,b)=>comparators[metric](a,b)||a.name.localeCompare(b.name))}
function render(){let st=stats(),rank=sortedPlayers(st),points=sortedPlayers(st,'points').find(x=>x.m),win=sortedPlayers(st.filter(x=>x.m),'rate')[0],mvp=sortedPlayers(st.filter(x=>x.motm),'mvp')[0],scorer=sortedPlayers(st.filter(x=>x.goals),'goals')[0],attendance=sortedPlayers(st.filter(x=>x.m),'attendance')[0];
$('#heroStats').innerHTML=`<div class="hero-stat"><strong>${data.matches.length}</strong><span>matchs joués</span></div><div class="hero-stat"><strong>${data.players.length}</strong><span>joueurs inscrits</span></div><div class="hero-stat"><strong>${esc(playerLabel(points))}</strong><span>leader actuel</span></div>`;
$('#trophyGrid').innerHTML=[['🏆','Leader aux points',points,points?`${points.points} points`:'Aucun match','points'],['⚡','Meilleur taux de victoire',win,win?`${win.rate}% de victoires`:'Aucun match','rate'],['⚽','Meilleur buteur',scorer,scorer?`${scorer.goals} but${scorer.goals>1?'s':''}`:'Aucun but','goals'],['⭐','MVP de la saison',mvp,mvp?`${mvp.motm} élection${mvp.motm>1?'s':''}`:'Pas encore élu','mvp'],['🎽','Plus assidu',attendance,attendance?`${attendance.m} match${attendance.m>1?'s':''}`:'Aucun match','attendance']].map(([i,t,p,v,key])=>`<button class="trophy" type="button" data-ranking="${key}"><span class="trophy-icon">${i}</span><p class="eyebrow">${t}</p><h3>${esc(playerLabel(p))}</h3><p>${v}</p><span class="trophy-action">Voir le top 3 →</span></button>`).join('');
$('#rankingBody').innerHTML=rank.map((p,i)=>`<tr><td>${i+1}</td><td class="namecell">${esc(playerLabel(p))}${p.motm?' ⭐':''}</td><td>${p.m}</td><td>${p.w}</td><td>${p.d}</td><td>${p.l}</td><td><b>${p.points}</b></td><td><b>${p.goals}</b></td><td>${p.rate}%</td></tr>`).join('')||'<tr><td colspan="9">Aucun joueur.</td></tr>';
$('#matchList').innerHTML=[...data.matches].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="match"><span class="match-date">${new Date(x.date+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</span><div class="match-teams"><div class="score-line">${+x.scoreA||0} — ${+x.scoreB||0}</div>Team A <span>${x.a.map(n=>esc(labelForName(n))).join(', ')}</span><br>Team B <span>${x.b.map(n=>esc(labelForName(n))).join(', ')}</span></div><div><span class="result-badge">${x.result==='N'?'Égalité':`Victoire Team ${x.result}`}</span>${x.motm?` <small>⭐ ${esc(labelForName(x.motm))}</small>`:''}</div></article>`).join('')||'<p class="muted">Aucun match pour le moment.</p>';
$('#playerGrid').innerHTML=[...st].sort((a,b)=>playerLabel(a).localeCompare(playerLabel(b))).map(p=>`<button class="player" data-player="${esc(p.name)}">${avatar(p)}<h3>${esc(playerLabel(p))}</h3><p>${p.m} match${p.m>1?'s':''} · ${p.rate}% de victoires · ${p.motm} MVP</p><span class="profile-link">Voir la fiche →</span></button>`).join('')||'<p class="muted">Aucun joueur.</p>';
renderPlayerAnalytics(st);$('#connectionStatus').textContent=cloud?(admin(false)?'Admin connecté':'Stats partagées'):'Mode démo';drawComposer()}
function metric(value,label,key,accent=''){return`<div class="metric ${accent}"><button class="info-button metric-info" type="button" data-info-key="${key}" aria-label="Comment est calculée la statistique ${esc(label)} ?">i</button><b>${value}</b><span>${label}</span></div>`}
function renderPlayerAnalytics(st=stats()){if(!$('#profileDonut'))return;let selected=$('#profileFilter').value,keys=['attaque','milieu','defense','gardien','polyvalent'],counts=Object.fromEntries(keys.map(k=>[k,st.filter(p=>(p.position||'polyvalent')===k).length])),total=Math.max(st.length,1),cursor=0,stops=keys.map(k=>{let start=cursor,end=cursor+counts[k]/total*360;cursor=end;return`${positionMeta[k].color} ${start}deg ${end}deg`});$('#profileDonut').style.background=st.length?`conic-gradient(${stops.join(',')})`:'#e7e9e4';$('#profileDonut').innerHTML=`<span><b>${selected==='all'?st.length:counts[selected]}</b><small>${selected==='all'?'joueurs':positionMeta[selected].label+(counts[selected]>1?'s':'')}</small></span>`;$('#profileLegend').innerHTML=keys.map(k=>`<button type="button" data-profile-filter="${k}" class="${selected===k?'active':''}"><i style="background:${positionMeta[k].color}"></i><span>${positionMeta[k].label}${counts[k]>1?'s':''}</span><b>${counts[k]}</b></button>`).join('');let max=Math.max(...Object.values(counts),1);$('#profileBars').innerHTML=keys.map(k=>`<div class="profile-bar"><span>${positionMeta[k].label}</span><div><i style="width:${counts[k]/max*100}%;background:${positionMeta[k].color}"></i></div><b>${counts[k]}</b></div>`).join('');let filtered=selected==='all'?st:st.filter(p=>(p.position||'polyvalent')===selected);$('#profileFilteredPlayers').innerHTML=filtered.map(p=>`<button type="button" class="profile-dot-card" data-player="${esc(p.name)}"><i style="background:${positionMeta[p.position||'polyvalent'].color}"></i>${avatar(p,'mini-avatar')}<span><b>${esc(playerLabel(p))}</b><small>${positionMeta[p.position||'polyvalent'].label} · ${p.rate}% V · ${p.goals} but${p.goals>1?'s':''}</small></span></button>`).join('')||'<p class="muted">Aucun joueur dans ce profil.</p>'}
async function cloudLoad(){let[p,m,x]=await Promise.all([db.from('players').select('id,name,last_name,position,avatar_url,active').eq('active',true).order('name'),db.from('matches').select('id,date,result,score_a,score_b,motm:players!matches_motm_id_fkey(name)').order('date',{ascending:false}),db.from('participations').select('match_id,player_id,team,goals,player:players(name)')]);if(x.error&&/goals/i.test(x.error.message)){goalsReady=false;x=await db.from('participations').select('match_id,player_id,team,player:players(name)')}else goalsReady=true;if(p.error||m.error||x.error)throw p.error||m.error||x.error;data.players=p.data;data.matches=m.data.map(v=>{let rows=x.data.filter(q=>q.match_id===v.id);return{id:v.id,date:v.date,result:v.result,scoreA:v.score_a,scoreB:v.score_b,motm:v.motm?.name||'',a:rows.filter(q=>q.team==='A').map(q=>q.player.name),b:rows.filter(q=>q.team==='B').map(q=>q.player.name),goals:Object.fromEntries(rows.map(q=>[q.player.name,+q.goals||0]))}});composeSheet=composeSheet.filter(n=>player(n));render()}
async function init(){if(!cfg())return render();db=supabase.createClient(cfg().url,cfg().key);cloud=true;user=(await db.auth.getSession()).data.session?.user;db.auth.onAuthStateChange((_e,s)=>{user=s?.user;render()});try{await cloudLoad()}catch(e){console.error(e);toast('Impossible de charger les données Supabase.');render()}}
function closeDialog(d){d.close();if(d.id==='matchDialog')resetMatch();if(d.id==='playerDialog')$('#playerDialog form').reset()}
$$('.close').forEach(b=>b.onclick=()=>closeDialog(b.closest('dialog')));$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)closeDialog(d)});
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.page').forEach(e=>e.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active');if(b.dataset.page==='composer')drawComposer()});
$('#addPlayerBtn').onclick=()=>{if(admin()){$('#playerDialog form').reset();$('#playerDialog').showModal()}};
$('#savePlayerBtn').onclick=async()=>{let name=$('#playerName').value.trim(),last_name=$('#playerLastName').value.trim(),avatar_url=$('#playerAvatarUrl').value.trim()||null,position=$('#playerPosition').value;if(!name)return toast('Ajoute au moins un prénom.');if(!validAvatarUrl(avatar_url))return toast('L’URL de la photo doit commencer par http:// ou https://.');if(data.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast('Ce prénom existe déjà.');if(cloud){let r=await db.from('players').insert({name,last_name:last_name||null,avatar_url,position});if(r.error)return toast(r.error.message);await cloudLoad()}else{data.players.push({id:crypto.randomUUID(),name,last_name,position,avatar_url,active:true});render()}closeDialog($('#playerDialog'));toast(`${name} a rejoint l’effectif.`)};
function chip(name,context,zone){let b=document.createElement('button');b.type='button';b.className='drag-player';b.draggable=true;b.dataset.name=name;b.innerHTML=`${avatar(player(name),'mini-avatar')}<span>${esc(labelForName(name))}</span>`;b.ondragstart=e=>{e.dataTransfer.setData('text/plain',JSON.stringify({name,context}));e.dataTransfer.effectAllowed='move'};b.onclick=()=>context==='match'?moveMatch(name,zone==='pool'?(matchDraft.A.length<=matchDraft.B.length?'A':'B'):'pool'):moveCompose(name,zone==='bench'?'sheet':'bench');return b}
function bindZones(sel,context,mover){$$(sel).forEach(z=>{z.ondragover=e=>{e.preventDefault();z.classList.add('over')};z.ondragleave=()=>z.classList.remove('over');z.ondrop=e=>{e.preventDefault();z.classList.remove('over');try{let p=JSON.parse(e.dataTransfer.getData('text/plain'));if(p.context===context)mover(p.name,z.dataset[context==='match'?'matchZone':'composeZone'])}catch(_){}}})}
function resetMatch(){matchDraft={A:[],B:[]};$('#matchDate').value='';$('#scoreA').value=$('#scoreB').value=0;$('#motm').innerHTML='<option value="">— Sélectionner —</option>';matchStep(1);drawMatch()}
function moveMatch(n,to){matchDraft.A=matchDraft.A.filter(x=>x!==n);matchDraft.B=matchDraft.B.filter(x=>x!==n);if(to==='A'||to==='B')matchDraft[to].push(n);drawMatch()}
function drawMatch(){let z={A:$('#matchTeamA'),B:$('#matchTeamB'),pool:$('#matchPool')};Object.values(z).forEach(e=>e.innerHTML='');matchDraft.A.forEach(n=>z.A.append(chip(n,'match','A')));matchDraft.B.forEach(n=>z.B.append(chip(n,'match','B')));let pool=data.players.map(p=>p.name).filter(n=>!matchDraft.A.includes(n)&&!matchDraft.B.includes(n));pool.forEach(n=>z.pool.append(chip(n,'match','pool')));$('#availableCount').textContent=pool.length;$('#motm').innerHTML='<option value="">— Sélectionner —</option>'+[...matchDraft.A,...matchDraft.B].map(n=>`<option value="${esc(n)}">${esc(labelForName(n))}</option>`).join('')}
function matchStep(n){$$('.match-step').forEach(s=>s.classList.toggle('active',s.id===(n===1?'matchStepTeams':'matchStepResult')));$$('[data-step-indicator]').forEach(s=>s.classList.toggle('active',+s.dataset.stepIndicator===n))}
function resultPreview(){let a=+$('#scoreA').value,b=+$('#scoreB').value;$('#resultPreview').textContent=a===b?'Égalité':a>b?'Victoire Team A':'Victoire Team B'}
$('#addMatchBtn').onclick=()=>{if(!admin())return;resetMatch();$('#matchDate').value=new Date().toISOString().slice(0,10);drawMatch();$('#matchDialog').showModal()};
$('#continueMatchBtn').onclick=()=>{if(!matchDraft.A.length||!matchDraft.B.length)return toast('Place au moins un joueur dans chaque équipe.');if(Math.abs(matchDraft.A.length-matchDraft.B.length)>1)return toast('Les équipes doivent avoir presque le même nombre de joueurs.');if(!$('#matchDate').value)return toast('Choisis la date du match.');matchStep(2);resultPreview()};
$('#backMatchBtn').onclick=()=>matchStep(1);$('#scoreA').oninput=$('#scoreB').oninput=resultPreview;
$('#saveMatchBtn').onclick=async()=>{let scoreA=+$('#scoreA').value,scoreB=+$('#scoreB').value,motm=$('#motm').value;if(!Number.isInteger(scoreA)||!Number.isInteger(scoreB)||scoreA<0||scoreB<0)return toast('Entre deux scores valides.');if(!motm)return toast('Sélectionne l’homme du match.');let result=scoreA===scoreB?'N':scoreA>scoreB?'A':'B';if(cloud){let ids=Object.fromEntries(data.players.map(p=>[p.name,p.id])),ins=await db.from('matches').insert({date:$('#matchDate').value,result,motm_id:ids[motm],score_a:scoreA,score_b:scoreB}).select().single();if(ins.error)return toast(ins.error.message);let rows=[...matchDraft.A.map(n=>({match_id:ins.data.id,player_id:ids[n],team:'A'})),...matchDraft.B.map(n=>({match_id:ins.data.id,player_id:ids[n],team:'B'}))],q=await db.from('participations').insert(rows);if(q.error){await db.from('matches').delete().eq('id',ins.data.id);return toast(`Match annulé : ${q.error.message}`)}await cloudLoad()}else{data.matches.push({id:crypto.randomUUID(),date:$('#matchDate').value,result,motm,scoreA,scoreB,a:[...matchDraft.A],b:[...matchDraft.B]});render()}closeDialog($('#matchDialog'));toast('Match enregistré !')};
async function openProfile(name){let p=player(name),s=stats().find(x=>x.name===name),mate=teammateInsight(name),chance=clamp(Math.round(35+strength(name)*.3),35,65),form=s.recent.length?s.recent.map(x=>`<span class="form-dot ${x.toLowerCase()}">${x}</span>`).join(''):'<span class="muted">Pas encore de match</span>',history=[...data.matches].filter(x=>x.a.includes(name)||x.b.includes(name)).sort((a,b)=>b.date.localeCompare(a.date));let historyHtml=history.map(x=>{let side=x.a.includes(name)?'A':'B',won=x.result===side,label=x.result==='N'?'Égalité':won?'Victoire':'Défaite',mates=(side==='A'?x.a:x.b).filter(n=>n!==name),opponents=side==='A'?x.b:x.a,g=+x.goals?.[name]||0;return`<article class="history-match" data-goal-match="${x.id}"><div class="history-date">${new Date(x.date+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}<span class="history-result ${label.toLowerCase().replace('é','e')}">${label}</span></div><div class="history-score"><b>${+x.scoreA||0} — ${+x.scoreB||0}</b><span>Team ${side}</span></div><div class="history-teams"><small>Avec</small> ${esc(mates.map(labelForName).join(', ')||'—')}<br><small>Contre</small> ${esc(opponents.map(labelForName).join(', ')||'—')}</div><div class="history-goals"><b>${g}</b><span>but${g>1?'s':''}</span></div>${admin(false)?`<div class="goal-controls"><label>Buts marqués<input type="number" min="0" max="99" value="${g}" inputmode="numeric"></label><button class="primary save-goals" type="button">Enregistrer</button></div>`:''}</article>`}).join('')||'<p class="muted">Aucun match joué pour le moment.</p>';
$('#playerDetailBody').innerHTML=`<div class="profile-head">${avatar(p,'profile-avatar')}<div><p class="eyebrow">FICHE JOUEUR</p><h2>${esc(playerLabel(p))}</h2><p class="position-tag">${positionMeta[p.position||'polyvalent'].label}</p></div>${admin(false)?'<button class="edit-profile-btn" id="editProfileBtn" type="button" aria-label="Modifier la fiche du joueur">✏️</button>':''}</div><div class="profile-stats">${metric(s.m,'participations','matches')}${metric(`${s.rate}%`,'taux de victoire','rate')}${metric(s.goals,'buts marqués','goals')}${metric(s.ppg,'points / match','ppg')}${metric(s.motm,'MVP','mvp')}${metric(`${s.diff>0?'+':''}${s.diff}`,'diff. de buts','diff')}${metric(`${chance}%`,'de chance de gagner avec ce profil dans ton équipe','chance','accent')}</div><div class="insights"><div><small>FORME · 5 DERNIERS MATCHS</small><p class="form-row">${form}</p></div><div><small>MEILLEURE ASSOCIATION</small><p>${mate?`<b>${esc(labelForName(mate.teammate))}</b> · ${mate.rate}% sur ${mate.games} match${mate.games>1?'s':''}`:'Pas assez de données'}</p></div></div><section class="player-history"><div class="history-heading"><div><p class="eyebrow">HISTORIQUE</p><h3>Matchs joués</h3></div><span>${history.length} match${history.length>1?'s':''}</span></div>${!goalsReady&&admin(false)?'<p class="migration-warning">Active la colonne des buts dans Supabase pour pouvoir les enregistrer.</p>':''}${historyHtml}</section><p class="model-note">Les probabilités combinent taux de victoire, points par match, différence de buts et volume de matchs. Elles deviennent plus fiables avec davantage de résultats.</p>${admin(false)?`<div class="profile-form" id="profileEditForm" hidden><div class="edit-form-title"><h3>Modifier le joueur</h3><button class="secondary compact" id="cancelProfileEditBtn" type="button">Annuler</button></div><div class="edit-name-grid"><label>Prénom<input id="editPlayerName" maxlength="24" value="${esc(p.name)}"></label><label>Nom (facultatif)<input id="editPlayerLastName" maxlength="32" value="${esc(p.last_name||'')}"></label></div><label>Photo de profil (URL)<input id="avatarUrl" type="url" value="${esc(p.avatar_url||'')}" placeholder="https://…"></label><label>Profil<select id="detailPosition"><option value="attaque">Attaque</option><option value="milieu">Milieu</option><option value="defense">Défense</option><option value="gardien">Gardien</option><option value="polyvalent">Polyvalent</option></select></label><div class="modal-actions"><button class="danger" id="deletePlayerBtn" type="button">Supprimer le joueur</button><button class="primary" id="saveProfileBtn" type="button">Enregistrer les modifications</button></div></div>`:''}`;$('#playerDetail').showModal();
$('#playerDetailBody').onclick=async e=>{let save=e.target.closest('.save-goals'),card=e.target.closest('.history-match'),controls=e.target.closest('.goal-controls');if(save){e.stopPropagation();if(!goalsReady)return toast('Exécute d’abord la migration Supabase des buts.');let match=data.matches.find(x=>x.id===card.dataset.goalMatch),value=+card.querySelector('input').value,side=match.a.includes(name)?'A':'B',team=side==='A'?match.a:match.b,max=side==='A'?+match.scoreA:+match.scoreB,others=team.filter(n=>n!==name).reduce((z,n)=>z+(+match.goals?.[n]||0),0);if(!Number.isInteger(value)||value<0)return toast('Entre un nombre de buts valide.');if(value+others>max)return toast(`Le total des buteurs dépasse les ${max} buts de l’équipe.`);if(cloud){let r=await db.from('participations').update({goals:value}).eq('match_id',match.id).eq('player_id',p.id);if(r.error)return toast(r.error.message);await cloudLoad()}else{match.goals=match.goals||{};match.goals[name]=value;render()}await openProfile(name);toast('Nombre de buts enregistré.')}else if(card&&admin(false)&&!controls)card.classList.toggle('editing')};
if(!admin(false))return;$('#detailPosition').value=p.position||'polyvalent';$('#editProfileBtn').onclick=()=>{$('#profileEditForm').hidden=false;$('#editProfileBtn').hidden=true;$('#editPlayerName').focus()};$('#cancelProfileEditBtn').onclick=()=>{$('#profileEditForm').hidden=true;$('#editProfileBtn').hidden=false};$('#saveProfileBtn').onclick=async()=>{let newName=$('#editPlayerName').value.trim(),u={name:newName,last_name:$('#editPlayerLastName').value.trim()||null,position:$('#detailPosition').value,avatar_url:$('#avatarUrl').value.trim()||null};if(!newName)return toast('Le prénom ne peut pas être vide.');if(!validAvatarUrl(u.avatar_url))return toast('L’URL de la photo doit commencer par http:// ou https://.');if(data.players.some(x=>x.id!==p.id&&x.name.toLowerCase()===newName.toLowerCase()))return toast('Ce prénom est déjà utilisé.');if(cloud){let r=await db.from('players').update(u).eq('id',p.id);if(r.error)return toast(r.error.message);await cloudLoad()}else{let oldName=p.name;data.matches.forEach(x=>{x.a=x.a.map(n=>n===oldName?newName:n);x.b=x.b.map(n=>n===oldName?newName:n);if(x.motm===oldName)x.motm=newName;if(x.goals&&Object.hasOwn(x.goals,oldName)){x.goals[newName]=x.goals[oldName];delete x.goals[oldName]}});Object.assign(p,u)}closeDialog($('#playerDetail'));render();toast('Fiche mise à jour.')};$('#deletePlayerBtn').onclick=async()=>{if(!confirm(`Retirer ${name} de l’effectif ? Son historique sera conservé.`))return;if(cloud){let r=await db.from('players').update({active:false}).eq('id',p.id);if(r.error)return toast(r.error.message);await cloudLoad()}else data.players=data.players.filter(x=>x.id!==p.id);closeDialog($('#playerDetail'));render();toast(`${name} a été retiré de l’effectif.`)}}
$('#playerGrid').onclick=e=>{let c=e.target.closest('[data-player]');if(c)openProfile(c.dataset.player)};
$('#rankingSort').onchange=e=>{rankingSort=e.target.value;render()};
$('#trophyGrid').onclick=e=>{let card=e.target.closest('[data-ranking]');if(!card)return;let key=card.dataset.ranking,st=stats().filter(p=>p.m&&(key!=='goals'||p.goals>0)&&(key!=='mvp'||p.motm>0)),titles={points:'Classement aux points',rate:'Meilleurs taux de victoire',goals:'Meilleurs buteurs',mvp:'Classement MVP',attendance:'Joueurs les plus assidus'},values={points:p=>`${p.points} point${p.points>1?'s':''}`,rate:p=>`${p.rate}% de victoires`,goals:p=>`${p.goals} but${p.goals>1?'s':''}`,mvp:p=>`${p.motm} MVP`,attendance:p=>`${p.m} match${p.m>1?'s':''}`},top=sortedPlayers(st,key).slice(0,3);$('#rankingDialogTitle').textContent=titles[key];$('#rankingPodium').innerHTML=top.map((p,i)=>`<article class="podium-row rank-${i+1}"><span class="medal">${['🥇','🥈','🥉'][i]}</span>${avatar(p,'mini-avatar')}<div><b>${esc(playerLabel(p))}</b><small>${values[key](p)}</small></div></article>`).join('')||'<p class="muted">Pas encore assez de données.</p>';$('#rankingDialog').showModal()};
document.addEventListener('click',e=>{let info=e.target.closest('[data-info-key]');if(!info)return;e.stopPropagation();let content=infoTexts[info.dataset.infoKey];if(!content)return;$('#infoDialogTitle').textContent=content[0];$('#infoDialogText').textContent=content[1];$('#infoDialog').showModal()});
$$('.subtab').forEach(b=>b.onclick=()=>{$$('.subtab').forEach(x=>x.classList.toggle('active',x===b));$('#playerCardsView').classList.toggle('active',b.dataset.playerView==='cards');$('#playerAnalyticsView').classList.toggle('active',b.dataset.playerView==='analytics');if(b.dataset.playerView==='analytics')renderPlayerAnalytics()});
$('#profileFilter').onchange=()=>renderPlayerAnalytics();$('#profileLegend').onclick=e=>{let b=e.target.closest('[data-profile-filter]');if(!b)return;$('#profileFilter').value=b.dataset.profileFilter;renderPlayerAnalytics()};$('#profileFilteredPlayers').onclick=e=>{let c=e.target.closest('[data-player]');if(c)openProfile(c.dataset.player)};
function moveCompose(n,to){composeSheet=composeSheet.filter(x=>x!==n);if(to==='sheet')composeSheet.push(n);drawComposer()}
function drawComposer(){if(!$('#composeBench'))return;let bench=data.players.map(p=>p.name).filter(n=>!composeSheet.includes(n));$('#composeBench').innerHTML=$('#composeSheet').innerHTML='';bench.forEach(n=>$('#composeBench').append(chip(n,'compose','bench')));composeSheet.forEach(n=>$('#composeSheet').append(chip(n,'compose','sheet')));$('#benchCount').textContent=bench.length;$('#sheetCount').textContent=composeSheet.length}
function balance(A,B){let a=power(A)/Math.max(A.length,1),b=power(B)/Math.max(B.length,1),pa=A.reduce((z,n)=>z+pos(player(n)?.position),0),pb=B.reduce((z,n)=>z+pos(player(n)?.position),0);return Math.abs(a-b)+Math.abs(pa-pb)*4+Math.abs(A.length-B.length)*30}
function fair(names){let best;for(let i=0;i<Math.min(1200,Math.max(200,names.length*100));i++){let m=shuffle(names),k=Math.ceil(m.length/2),c={A:m.slice(0,k),B:m.slice(k)};c.score=balance(c.A,c.B);if(!best||c.score<best.score)best=c}return best}
function human(names){if(names.length<4)return random(names);let ranked=[...names].sort((a,b)=>strength(b)-strength(a)),pair=Math.random()<.5?ranked.slice(0,2):ranked.slice(-2),rest=shuffle(ranked.filter(n=>!pair.includes(n))),A=[...pair],B=[];rest.forEach(n=>{let t=A.length>=Math.ceil(names.length/2)?B:B.length>=Math.floor(names.length/2)?A:balance([...A,n],B)<=balance(A,[...B,n])?A:B;t.push(n)});return{A,B}}
function random(names){let m=shuffle(names),k=Math.ceil(m.length/2);return{A:m.slice(0,k),B:m.slice(k)}}
function showTeams(t){let p=probability(t.A,t.B),team=(label,a)=>`<article class="generated-team"><p class="eyebrow">${label}</p>${a.map(n=>`<div class="generated-player">${avatar(player(n),'mini-avatar')}<span>${esc(labelForName(n))}</span><small>${Math.round(strength(n))}</small></div>`).join('')}</article>`;$('#builderResult').innerHTML=`<div class="generated-grid">${team('TEAM A',t.A)}${team('TEAM B',t.B)}<div class="odds"><div class="odds-head"><span>Team A · ${p}%</span><b>Pronostic</b><span>Team B · ${100-p}%</span></div><div class="odds-bar"><i style="width:${p}%"></i></div><small>Estimation statistique, pas une certitude : chaque match garde sa surprise.</small></div></div>`}
$$('.mode').forEach(b=>b.onclick=()=>{composeMode=b.dataset.mode;$$('.mode').forEach(x=>x.classList.toggle('active',x===b))});$('#generateTeamsBtn').onclick=()=>{if(composeSheet.length<2)return toast('Ajoute au moins deux joueurs à la feuille de match.');showTeams(composeMode==='fair'?fair(composeSheet):composeMode==='human'?human(composeSheet):random(composeSheet))};
$('#settingsBtn').onclick=()=>{let p=$('#accountPanel');p.innerHTML=cloud?(user?`<p class="muted">Connecté : <b>${esc(user.email)}</b>${admin(false)?' — administrateur':' — lecture seule'}</p><button class="primary wide" id="logoutBtn" type="button">Se déconnecter</button>`:'<label>E-mail administrateur<input id="emailInput" type="email" placeholder="prenom@email.com"></label><button class="primary wide" id="loginBtn" type="button">Recevoir mon lien administrateur</button>'):'<p class="muted">Mode de démonstration local.</p>';$('#settingsDialog').showModal();$('#loginBtn')?.addEventListener('click',async()=>{let email=$('#emailInput').value.trim().toLowerCase();if(!isAdminEmail(email))return toast('Cette adresse n’est pas autorisée.');let r=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});if(r.error)return toast(r.error.message);toast('Lien administrateur envoyé.')});$('#logoutBtn')?.addEventListener('click',async()=>{await db.auth.signOut();closeDialog($('#settingsDialog'))})};
bindZones('[data-match-zone]','match',moveMatch);bindZones('[data-compose-zone]','compose',moveCompose);if(cfg())init();else render();
