// Évolutions d'interface : profils, score et composition d'équipes.
let draft={A:[],B:[]};
const U=s=>document.querySelector(s),UA=s=>[...document.querySelectorAll(s)],closeAll=()=>UA('dialog[open]').forEach(d=>d.close());
UA('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function selectable(name,zone){let b=document.createElement('button');b.className='drag-player';b.textContent=name;b.draggable=true;b.dataset.name=name;b.onclick=()=>move(name,zone==='pool'?'A':'pool');b.ondragstart=e=>e.dataTransfer.setData('text/plain',name);return b}
function move(name,to){draft.A=draft.A.filter(x=>x!==name);draft.B=draft.B.filter(x=>x!==name);if(to==='A')draft.A.push(name);if(to==='B')draft.B.push(name);drawDraft()}
function drawDraft(){let all=data.players;let zones={A:U('#dropA'),B:U('#dropB'),pool:U('#playerPool')};Object.values(zones).forEach(x=>x.innerHTML='');draft.A.forEach(n=>zones.A.append(selectable(n,'A')));draft.B.forEach(n=>zones.B.append(selectable(n,'B')));all.filter(n=>!draft.A.includes(n)&&!draft.B.includes(n)).forEach(n=>zones.pool.append(selectable(n,'pool')));U('#motm').innerHTML='<option value="">— Sélectionner —</option>'+[...draft.A,...draft.B].map(n=>`<option>${n}</option>`).join('');let a=+U('#scoreA').value||0,b=+U('#scoreB').value||0;U('#resultPreview').textContent=a===b?'Égalité':a>b?'Victoire Team A':'Victoire Team B'}
['#dropA','#dropB','#playerPool'].forEach(sel=>{let z=U(sel),to=sel==='#dropA'?'A':sel==='#dropB'?'B':'pool';z.ondragover=e=>{e.preventDefault();z.classList.add('over')};z.ondragleave=()=>z.classList.remove('over');z.ondrop=e=>{e.preventDefault();z.classList.remove('over');move(e.dataTransfer.getData('text/plain'),to)}});
U('#addMatchBtn').onclick=()=>{if(!admin())return;draft={A:[],B:[]};U('#matchDate').value=new Date().toISOString().slice(0,10);U('#scoreA').value=0;U('#scoreB').value=0;drawDraft();U('#matchDialog').showModal()};UA('#scoreA,#scoreB').forEach(x=>x.oninput=drawDraft);
U('#saveMatchBtn').onclick=async()=>{let a=draft.A,b=draft.B,sa=+U('#scoreA').value,sb=+U('#scoreB').value,m=U('#motm').value;if(!a.length||!b.length||!m||sa<0||sb<0){toast('Complète les équipes, le score et le MVP.');return}let r=sa===sb?'N':sa>sb?'A':'B';if(cloud){let pr=await db.from('players').select('id,name'),ids=Object.fromEntries(pr.data.map(x=>[x.name,x.id]));let ins=await db.from('matches').insert({date:U('#matchDate').value,result:r,motm_id:ids[m],score_a:sa,score_b:sb}).select().single();if(ins.error){toast(ins.error.message);return}let joins=[...a.map(n=>({match_id:ins.data.id,player_id:ids[n],team:'A'})),...b.map(n=>({match_id:ins.data.id,player_id:ids[n],team:'B'}))];let q=await db.from('participations').insert(joins);if(q.error){toast(q.error.message);return}await cloudLoad()}else{data.matches.push({date:U('#matchDate').value,a,b,result:r,motm:m,scoreA:sa,scoreB:sb});save();render()}U('#matchDialog').close();toast('Match enregistré !')};
U('#addPlayerBtn').onclick=()=>{if(!admin())return;U('#playerName').value='';U('#playerLastName').value='';U('#playerDialog').showModal()};U('#savePlayerBtn').onclick=async()=>{let n=U('#playerName').value.trim(),last=U('#playerLastName').value.trim(),pos=U('#playerPosition').value;if(!n){toast('Ajoute un prénom.');return}if(cloud){let r=await db.from('players').insert({name:n,last_name:last,position:pos});if(r.error){toast(r.error.message);return}await cloudLoad()}else{data.players.push(n);save();render()}U('#playerDialog').close();toast(`${n} a rejoint l'effectif.`)};
async function profile(name){let row=cloud?(await db.from('players').select('*').eq('name',name).single()).data:{name,position:'polyvalent'};let s=stats().find(x=>x.name===name),teamRate=s?.m?s.rate:0,winTeam=teamRate;U('#playerDetailBody').innerHTML=`<div class="profile-head"><div class="profile-avatar">${row.avatar_url?`<img class="profile-avatar" src="${row.avatar_url}">`:name[0]}</div><div><p class="eyebrow">FICHE JOUEUR</p><h2>${name} ${row.last_name||''}</h2><p class="muted">${row.position||'polyvalent'}</p></div></div><div class="profile-stats"><div class="metric"><b>${s?.m||0}</b>participations</div><div class="metric"><b>${teamRate}%</b>taux de victoire</div><div class="metric"><b>${s?.motm||0}</b>MVP</div><div class="metric"><b>${winTeam}%</b>chance de gagner avec lui</div></div>${admin()?`<div class="profile-form"><label>Photo (URL)<input id="avatarUrl" value="${row.avatar_url||''}" placeholder="https://..." /></label><label>Profil<select id="detailPos"><option value="attaque">Attaque</option><option value="defense">Défense</option><option value="polyvalent">Polyvalent</option></select></label><button class="primary wide" id="saveProfile">Enregistrer la fiche</button><button class="danger delete-btn" id="deletePlayer">Supprimer ce joueur</button></div>`:''}`;if(row.position)U('#detailPos').value=row.position;U('#playerDetail').showModal();if(admin()){U('#saveProfile').onclick=async()=>{let r=await db.from('players').update({position:U('#detailPos').value,avatar_url:U('#avatarUrl').value.trim()||null}).eq('id',row.id);if(r.error)toast(r.error.message);else{U('#playerDetail').close();toast('Fiche mise à jour.')}};U('#deletePlayer').onclick=async()=>{if(!confirm(`Supprimer ${name} ?`))return;let r=await db.from('players').update({active:false}).eq('id',row.id);if(r.error)toast(r.error.message);else{U('#playerDetail').close();await cloudLoad();toast('Joueur supprimé.')}}}}
setInterval(()=>UA('.player').forEach(c=>c.onclick=()=>profile(c.querySelector('h3').textContent)),500);
U('#generateTeamsBtn').onclick=()=>{let n=UA('#builderPlayers input:checked').map(x=>x.value),mode=U('#builderMode').value;if(n.length<2){toast('Sélectionne au moins 2 joueurs.');return}let st=stats(),strength=x=>st.find(v=>v.name===x)?.rate||50,sh=[...n].sort(()=>Math.random()-.5);if(mode==='fair')sh.sort((a,b)=>strength(b)-strength(a));let A=[],B=[];sh.forEach(x=>{let sum=q=>q.reduce((z,v)=>z+strength(v),0);(sum(A)<=sum(B)?A:B).push(x)});if(mode==='random'){A.splice(0,A.length,...sh.slice(0,Math.ceil(sh.length/2)));B.splice(0,B.length,...sh.slice(Math.ceil(sh.length/2)))}U('#builderResult').innerHTML=`<div class="team-proposal"><b>Team A</b><ul>${A.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="team-proposal"><b>Team B</b><ul>${B.map(x=>`<li>${x}</li>`).join('')}</ul></div>`};
// Composer : attribution manuelle au banc / équipes, puis calcul d'équilibre.
let compose={A:[],B:[]},mode='fair';function drawCompose(){let z={A:U('#composeA'),B:U('#composeB'),pool:U('#composePool')};if(!z.A)return;Object.values(z).forEach(x=>x.innerHTML='');let add=(n,to)=>{let b=selectable(n,to);b.onclick=()=>{compose.A=compose.A.filter(x=>x!==n);compose.B=compose.B.filter(x=>x!==n);if(to==='pool')compose.A.push(n);else if(to==='A')compose.B.push(n);drawCompose()};z[to].append(b)};compose.A.forEach(n=>add(n,'A'));compose.B.forEach(n=>add(n,'B'));data.players.filter(n=>!compose.A.includes(n)&&!compose.B.includes(n)).forEach(n=>add(n,'pool'))}UA('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;UA('.mode').forEach(x=>x.classList.toggle('active',x===b))});U('#generateTeamsBtn').onclick=()=>{let all=[...compose.A,...compose.B];if(all.length<2){toast('Attribue au moins 2 joueurs.');return}let st=stats(),v=n=>st.find(x=>x.name===n)?.rate||50;if(!compose.A.length||!compose.B.length){let s=[...all].sort(()=>Math.random()-.5);compose={A:[],B:[]};s.forEach(n=>((compose.A.reduce((a,x)=>a+v(x),0)<=compose.B.reduce((a,x)=>a+v(x),0)?compose.A:compose.B).push(n));drawCompose()}let a=compose.A.reduce((x,n)=>x+v(n),0),b=compose.B.reduce((x,n)=>x+v(n),0),p=Math.round(a/(a+b)*100);U('#builderResult').innerHTML=`<div class="odds"><div class="odds-head"><span>Team A ${p}%</span><span>Team B ${100-p}%</span></div><div class="odds-bar"><i style="width:${p}%"></i></div><small>${mode==='fair'?'Équilibre optimisé':mode==='human'?'Équilibre avec une part de folie':'Répartition aléatoire'}</small></div>`};document.querySelector('[data-page="composer"]').addEventListener('click',drawCompose);drawCompose();
setInterval(()=>{if(cloud&&user)U('#connectionStatus').textContent=isAdminEmail(user.email)?'Admin connecté':'Lecture seule';UA('.match').forEach((card,i)=>{let m=[...data.matches].sort((a,b)=>b.date.localeCompare(a.date))[i];if(m?.scoreA!==undefined&&!card.querySelector('.score-line'))card.querySelector('.match-teams').insertAdjacentHTML('afterbegin',`<div class="score-line">${m.scoreA} — ${m.scoreB}</div>`)});},700);
